import { apiFetch } from "./apiClient";

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, "+")
    .replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export const pushNotificationService = {
  isSupported(): boolean {
    return (
      typeof window !== "undefined" &&
      "serviceWorker" in navigator &&
      "PushManager" in window &&
      "Notification" in window
    );
  },

  getPermissionState(): NotificationPermission {
    if (typeof window === "undefined" || !("Notification" in window)) {
      return "denied";
    }
    return Notification.permission;
  },

  async registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
    if (!this.isSupported()) return null;
    try {
      const reg = await navigator.serviceWorker.register("/sw.js", { scope: "/" });
      await navigator.serviceWorker.ready;
      return reg;
    } catch (err) {
      console.error("[Push] Service Worker registration failed:", err);
      return null;
    }
  },

  async getVapidPublicKey(): Promise<string> {
    const data = await apiFetch<{ publicKey: string }>("/notifications/vapid-public-key");
    return data.publicKey;
  },

  async subscribe(userId?: string | number): Promise<boolean> {
    if (!this.isSupported()) {
      throw new Error("Push notifications are not supported in this browser.");
    }

    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      throw new Error("Push notification permission was not granted.");
    }

    const registration = await this.registerServiceWorker();
    if (!registration) {
      throw new Error("Service Worker could not be registered.");
    }

    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      const publicKey = await this.getVapidPublicKey();
      const applicationServerKey = urlBase64ToUint8Array(publicKey) as unknown as BufferSource;

      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey,
      });
    }

    const rawSub = subscription.toJSON();
    if (!rawSub.endpoint || !rawSub.keys?.p256dh || !rawSub.keys?.auth) {
      throw new Error("Incomplete push subscription generated by browser.");
    }

    await apiFetch("/notifications/subscribe", {
      method: "POST",
      body: JSON.stringify({
        endpoint: rawSub.endpoint,
        keys: {
          p256dh: rawSub.keys.p256dh,
          auth: rawSub.keys.auth,
        },
        user_id: userId,
      }),
    });

    return true;
  },

  async sendTestAlert(): Promise<{ status: string; message: string; delivered: number }> {
    return await apiFetch<{ status: string; message: string; delivered: number }>(
      "/notifications/test",
      {
        method: "POST",
        body: JSON.stringify({
          title: "🔔 OpenTask Push Verification",
          body: "Push notification alert pipeline is active and verified!",
          url: "/notifications",
        }),
      }
    );
  },
};
