name: Build & Deploy Rust API

on:
  push:
    branches:
      - master
    paths:
      - 'opentask-api/**'
      - '.github/workflows/deploy-rust.yml'
  workflow_dispatch: # Allows manual trigger from GitHub UI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_name }}/opentask-rust-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./opentask-api
          file: ./opentask-api/Dockerfile
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deply-to-dewacloud:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on DewaCloud via SSH
        uses: appleboy/ssh-action@v1
        with: 
          username: ${{ vars.DEWACLOUD_SSH_USER }}
          key: ${{ secrets.DEWACLOUD_SSH_PRIVATE_KEY }}
          scripts:
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ env.IMAGE_NAME }}:latest
            docker stop rust-api || true
            docker rm rust-api || true
            docker run -d --name rust-api --restart unless-stopped -p 80:8000 --env-file ~/OpenTask/.env \
              ghcr.io/${{ env.IMAGE_NAME }}:latest
            docker image prune -af --filter "until=24h"
